### ISSUE TITLE
设置了category，但是该页面为空？

### ISSUE THREAD

**Issue by 349989153** [lazysheep666/terminal_theme#4]
## 为什么我觉得是该主题的issue？
tags页面也是按照下述步骤生成的，tags页面正确展示了。并且在相同的配置下，我把主题切换成next，categories页面亦能正确展示。

## 复现步骤：

1. 给文章的头加上categories：
```markdown
---
title: 阅读redux源码--compose.js
date: 2018-04-09 16:52:16
tags: [js, redux, 源码]
categories: 技术
---
```

2.生成categories的页面：
`hexo new page categories`

3. 修改source/categories/index.md:
```markdown
---
title: categories
date: 2018-04-10 11:11:33
type: "categories"
layout: categories
---

```
4. 修改themes/terminal/_config.yml，menu上加上categories：
```yaml
# main menu navigation
menu:
  Home: /
  About: /about
  Tags: /tags
  Categories: /categories
```

5. 重启：
```shell
hexo clean
hexo g
hexo s
```
## 现象
在Menu上点击“Categories”，然后这个页面上没有“技术”的分类。可以查看https://349989153.github.io/categories/

## 期望：
Categories页面正确显示所有分类。
